import { PublicMenuClient } from '@/components/public-menu/PublicMenuClient'

const demoRestaurant = {
  id: 'demo',
  name: 'La Pollería del Barrio',
  description: 'El mejor pollo a la brasa de Lima desde 1992',
  logoUrl: '/logo-demo.png',
  primaryColor: '#C0392B',
  bgColor: '#FFF8F0',
  district: 'San Borja',
  city: 'Lima',
  languages: ['es', 'en', 'pt'],
  categories: [
    {
      id: 'cat-1',
      name: 'Pollo a la Brasa',
      nameEn: 'Rotisserie Chicken',
      namePt: 'Frango Assado',
      order: 0,
      items: [
        {
          id: 'item-1',
          name: 'Pollo Entero',
          nameEn: 'Whole Chicken',
          namePt: 'Frango Inteiro',
          description: 'Pollo a la brasa entero con papas fritas y ensalada',
          descriptionEn: 'Whole rotisserie chicken with fries and salad',
          descriptionPt: 'Frango assado inteiro com batata frita e salada',
          price: 52.00,
          imageUrl: null,
          isAvailable: true,
          allergens: [],
          order: 0,
        },
        {
          id: 'item-2',
          name: '1/2 Pollo',
          nameEn: 'Half Chicken',
          namePt: '1/2 Frango',
          description: 'Media porción con papas fritas y ensalada',
          descriptionEn: 'Half portion with fries and salad',
          descriptionPt: 'Meia porção com batata frita e salada',
          price: 29.00,
          imageUrl: null,
          isAvailable: true,
          allergens: [],
          order: 1,
        },
        {
          id: 'item-3',
          name: '1/4 Pollo',
          nameEn: 'Quarter Chicken',
          namePt: '1/4 Frango',
          description: 'Pierna o pechuga con papas fritas',
          descriptionEn: 'Leg or breast with fries',
          descriptionPt: 'Coxa ou peito com batata frita',
          price: 18.00,
          imageUrl: null,
          isAvailable: true,
          allergens: [],
          order: 2,
        },
        {
          id: 'item-4',
          name: 'Combo Familiar',
          nameEn: 'Family Combo',
          namePt: 'Combo Familiar',
          description: '2 pollos enteros + 4 gaseosas + 2 ensaladas grandes',
          descriptionEn: '2 whole chickens + 4 sodas + 2 large salads',
          descriptionPt: '2 frangos inteiros + 4 refrigerantes + 2 saladas grandes',
          price: 95.00,
          imageUrl: null,
          isAvailable: true,
          allergens: [],
          order: 3,
        },
      ],
    },
    {
      id: 'cat-2',
      name: 'Anticuchos y Parrilla',
      nameEn: 'Skewers & Grill',
      namePt: 'Espetinhos e Grelha',
      order: 1,
      items: [
        {
          id: 'item-5',
          name: 'Anticuchos',
          nameEn: 'Beef Heart Skewers',
          namePt: 'Anticuchos',
          description: 'Corazón de res marinado a la parrilla, con choclo y papa',
          descriptionEn: 'Grilled marinated beef heart with corn and potato',
          descriptionPt: 'Coração bovino marinado na grelha, com milho e batata',
          price: 22.00,
          imageUrl: null,
          isAvailable: true,
          allergens: [],
          order: 0,
        },
        {
          id: 'item-6',
          name: 'Chuletas a la Parrilla',
          nameEn: 'Grilled Pork Chops',
          namePt: 'Costeletas Grelhadas',
          description: 'Con papas doradas y ensalada fresca',
          descriptionEn: 'With golden potatoes and fresh salad',
          descriptionPt: 'Com batatas douradas e salada fresca',
          price: 32.00,
          imageUrl: null,
          isAvailable: true,
          allergens: [],
          order: 1,
        },
        {
          id: 'item-7',
          name: 'Rachi',
          nameEn: 'Grilled Tripe',
          namePt: 'Bucho Grelhado',
          description: 'Mondongo a la parrilla estilo criollo',
          descriptionEn: 'Grilled tripe Creole style',
          descriptionPt: 'Bucho grelhado estilo crioulo',
          price: 18.00,
          imageUrl: null,
          isAvailable: false,
          allergens: [],
          order: 2,
        },
      ],
    },
    {
      id: 'cat-3',
      name: 'Guarniciones',
      nameEn: 'Side Dishes',
      namePt: 'Acompanhamentos',
      order: 2,
      items: [
        {
          id: 'item-8',
          name: 'Papas Fritas',
          nameEn: 'French Fries',
          namePt: 'Batata Frita',
          description: 'Papas doradas crujientes',
          descriptionEn: 'Crispy golden fries',
          descriptionPt: 'Batatas douradas crocantes',
          price: 8.00,
          imageUrl: null,
          isAvailable: true,
          allergens: [],
          order: 0,
        },
        {
          id: 'item-9',
          name: 'Ensalada Criolla',
          nameEn: 'Creole Salad',
          namePt: 'Salada Criolla',
          description: 'Cebolla, tomate, ají amarillo y culantro',
          descriptionEn: 'Onion, tomato, yellow chili and cilantro',
          descriptionPt: 'Cebola, tomate, pimenta amarela e coentro',
          price: 6.00,
          imageUrl: null,
          isAvailable: true,
          allergens: [],
          order: 1,
        },
        {
          id: 'item-10',
          name: 'Yuca Frita',
          nameEn: 'Fried Yuca',
          namePt: 'Mandioca Frita',
          description: 'Yuca crocante con salsa criolla',
          descriptionEn: 'Crispy yuca with Creole sauce',
          descriptionPt: 'Mandioca crocante com molho crioulo',
          price: 9.00,
          imageUrl: null,
          isAvailable: true,
          allergens: [],
          order: 2,
        },
      ],
    },
    {
      id: 'cat-4',
      name: 'Bebidas',
      nameEn: 'Drinks',
      namePt: 'Bebidas',
      order: 3,
      items: [
        {
          id: 'item-11',
          name: 'Chicha Morada',
          nameEn: 'Purple Corn Drink',
          namePt: 'Chicha Morada',
          description: 'Casera, receta de la abuela',
          descriptionEn: 'Homemade, grandma\'s recipe',
          descriptionPt: 'Caseira, receita da vovó',
          price: 7.00,
          imageUrl: null,
          isAvailable: true,
          allergens: [],
          order: 0,
        },
        {
          id: 'item-12',
          name: 'Inca Kola',
          nameEn: 'Inca Kola',
          namePt: 'Inca Kola',
          description: 'Personal 500ml',
          descriptionEn: 'Personal 500ml',
          descriptionPt: 'Individual 500ml',
          price: 5.00,
          imageUrl: null,
          isAvailable: true,
          allergens: [],
          order: 1,
        },
        {
          id: 'item-13',
          name: 'Agua sin Gas',
          nameEn: 'Still Water',
          namePt: 'Água sem Gás',
          description: '625ml',
          descriptionEn: '625ml',
          descriptionPt: '625ml',
          price: 3.50,
          imageUrl: null,
          isAvailable: true,
          allergens: [],
          order: 2,
        },
      ],
    },
    {
      id: 'cat-5',
      name: 'Salsas',
      nameEn: 'Sauces',
      namePt: 'Molhos',
      order: 4,
      items: [
        {
          id: 'item-14',
          name: 'Ají Verde',
          nameEn: 'Green Chili Sauce',
          namePt: 'Molho Verde',
          description: 'Salsa de huacatay con ají amarillo, la clásica',
          descriptionEn: 'Huacatay sauce with yellow chili, the classic',
          descriptionPt: 'Molho de huacatay com pimenta amarela, o clássico',
          price: 3.00,
          imageUrl: null,
          isAvailable: true,
          allergens: [],
          order: 0,
        },
        {
          id: 'item-15',
          name: 'Crema de Rocoto',
          nameEn: 'Rocoto Cream',
          namePt: 'Creme de Rocoto',
          description: 'Para los que gustan del picante',
          descriptionEn: 'For spice lovers',
          descriptionPt: 'Para os amantes de picante',
          price: 3.00,
          imageUrl: null,
          isAvailable: true,
          allergens: [],
          order: 1,
        },
      ],
    },
  ],
}

export default function DemoPage() {
  return (
    <PublicMenuClient
      restaurant={demoRestaurant}
      initialLang="es"
      isDemo={true}
    />
  )
}
