import { PublicMenuClient } from '@/components/public-menu/PublicMenuClient'

const demoRestaurant = {
  id: 'demo',
  name: 'La Cevichería Limeña',
  description: 'Los mejores ceviches de Miraflores desde 1985',
  logoUrl: null,
  primaryColor: '#1B4F72',
  bgColor: '#EAF4FB',
  district: 'Miraflores',
  city: 'Lima',
  languages: ['es', 'en', 'pt'],
  categories: [
    {
      id: 'cat-1',
      name: 'Entradas',
      nameEn: 'Starters',
      namePt: 'Entradas',
      order: 0,
      items: [
        {
          id: 'item-1',
          name: 'Ceviche Clásico',
          nameEn: 'Classic Ceviche',
          namePt: 'Ceviche Clássico',
          description: 'Con leche de tigre, choclo y cancha serrana',
          descriptionEn: 'With tiger milk, corn and toasted cancha',
          descriptionPt: 'Com leite de tigre, milho e cancha tostada',
          price: 28.00,
          imageUrl: null,
          isAvailable: true,
          allergens: ['mariscos'],
          order: 0,
        },
        {
          id: 'item-2',
          name: 'Tiradito de Lenguado',
          nameEn: 'Flounder Tiradito',
          namePt: 'Tiradito de Linguado',
          description: 'Salsa amarilla, canchita tostada',
          descriptionEn: 'Yellow sauce, toasted canchita',
          descriptionPt: 'Molho amarelo, canchita tostada',
          price: 32.00,
          imageUrl: null,
          isAvailable: true,
          allergens: ['mariscos'],
          order: 1,
        },
        {
          id: 'item-3',
          name: 'Causa Limeña',
          nameEn: 'Lima-style Causa',
          namePt: 'Causa Limeña',
          description: 'Rellena de atún y palta',
          descriptionEn: 'Stuffed with tuna and avocado',
          descriptionPt: 'Recheada com atum e abacate',
          price: 18.00,
          imageUrl: null,
          isAvailable: false,
          allergens: ['mariscos'],
          order: 2,
        },
        {
          id: 'item-4',
          name: 'Leche de Tigre',
          nameEn: 'Tiger Milk',
          namePt: 'Leite de Tigre',
          description: 'El reconstituyente del mar',
          descriptionEn: 'The sea restorative',
          descriptionPt: 'O reconstituinte do mar',
          price: 15.00,
          imageUrl: null,
          isAvailable: true,
          allergens: ['mariscos'],
          order: 3,
        },
      ],
    },
    {
      id: 'cat-2',
      name: 'Platos de Fondo',
      nameEn: 'Main Courses',
      namePt: 'Pratos Principais',
      order: 1,
      items: [
        {
          id: 'item-5',
          name: 'Arroz con Mariscos',
          nameEn: 'Rice with Seafood',
          namePt: 'Arroz com Frutos do Mar',
          description: 'Con choros, camarones y conchas negras',
          descriptionEn: 'With mussels, shrimp and black clams',
          descriptionPt: 'Com mexilhões, camarões e mariscos',
          price: 42.00,
          imageUrl: null,
          isAvailable: true,
          allergens: ['mariscos'],
          order: 0,
        },
        {
          id: 'item-6',
          name: 'Chupe de Camarones',
          nameEn: 'Shrimp Chowder',
          namePt: 'Sopa de Camarões',
          description: 'Receta tradicional arequipeña',
          descriptionEn: 'Traditional Arequipa recipe',
          descriptionPt: 'Receita tradicional de Arequipa',
          price: 38.00,
          imageUrl: null,
          isAvailable: true,
          allergens: ['mariscos', 'lacteos'],
          order: 1,
        },
        {
          id: 'item-7',
          name: 'Jalea Mixta',
          nameEn: 'Mixed Fried Seafood',
          namePt: 'Frutos do Mar Fritos',
          description: 'Mariscos fritos, yuca y salsa criolla',
          descriptionEn: 'Fried seafood, yuca and criolla sauce',
          descriptionPt: 'Frutos do mar fritos, mandioca e molho crioulo',
          price: 45.00,
          imageUrl: null,
          isAvailable: true,
          allergens: ['mariscos', 'gluten'],
          order: 2,
        },
      ],
    },
    {
      id: 'cat-3',
      name: 'Bebidas',
      nameEn: 'Drinks',
      namePt: 'Bebidas',
      order: 2,
      items: [
        {
          id: 'item-8',
          name: 'Chicha Morada',
          nameEn: 'Purple Corn Drink',
          namePt: 'Chicha Morada',
          description: 'Casera, sin azúcar añadida',
          descriptionEn: 'Homemade, no added sugar',
          descriptionPt: 'Caseira, sem açúcar adicionado',
          price: 8.00,
          imageUrl: null,
          isAvailable: true,
          allergens: [],
          order: 0,
        },
        {
          id: 'item-9',
          name: 'Pisco Sour',
          nameEn: 'Pisco Sour',
          namePt: 'Pisco Sour',
          description: 'Receta de la casa',
          descriptionEn: 'House recipe',
          descriptionPt: 'Receita da casa',
          price: 22.00,
          imageUrl: null,
          isAvailable: true,
          allergens: ['huevo'],
          order: 1,
        },
        {
          id: 'item-10',
          name: 'Maracuyá Frozen',
          nameEn: 'Passion Fruit Frozen',
          namePt: 'Maracujá Frozen',
          description: null,
          descriptionEn: null,
          descriptionPt: null,
          price: 10.00,
          imageUrl: null,
          isAvailable: true,
          allergens: [],
          order: 2,
        },
      ],
    },
    {
      id: 'cat-4',
      name: 'Postres',
      nameEn: 'Desserts',
      namePt: 'Sobremesas',
      order: 3,
      items: [
        {
          id: 'item-11',
          name: 'Suspiro a la Limeña',
          nameEn: 'Lima-style Suspiro',
          namePt: 'Suspiro à Limeña',
          description: 'Con manjar blanco y merengue',
          descriptionEn: 'With dulce de leche and meringue',
          descriptionPt: 'Com doce de leite e merengue',
          price: 12.00,
          imageUrl: null,
          isAvailable: true,
          allergens: ['lacteos', 'huevo'],
          order: 0,
        },
        {
          id: 'item-12',
          name: 'Mazamorra Morada',
          nameEn: 'Purple Corn Pudding',
          namePt: 'Mazamorra Morada',
          description: 'Receta de abuela',
          descriptionEn: "Grandma's recipe",
          descriptionPt: 'Receita da vovó',
          price: 10.00,
          imageUrl: null,
          isAvailable: true,
          allergens: [],
          order: 1,
        },
      ],
    },
  ],
}

export default function DemoPage() {
  return (
    <PublicMenuClient
      restaurant={demoRestaurant}
      initialLang="es"
      isDemo={true}
    />
  )
}
